# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80cfc9f118573bc7a5cab1402cf87d2883d35065789fcbfd12a5f5503b087f9eb13446b4e02d15f799ce01701c705a65835934eed8b17efa3197114934e465fa

test:
  secret_key_base: a53bd9e9babe11a6a9e6a6e690ffcbf6ec1da84b2baae8df2712bb484fcb21f0ab6cacc03dae4bb425d2f552eb1303a3427e136b381a35ddc0359da2ae29482d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
